In [1]:
print("hello")

hello


In [3]:
def hello():
    print("Hello")
hello()    

Hello


In [4]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 1.8 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.3 MB 2.0 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.3 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.3 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.3 MB 2.0 MB/s eta 0:00:06
   ------- -------------------------------- 2.4/12.3 MB 1.9 MB/s eta 0:00:06
   --------- ------------------------------ 2.9/12.3 MB 1.9 MB/s eta 0:00:06
   ----------- ---------------------------- 3.4/12.3 MB 1.9 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.3 MB 1.9 MB/s eta 0:00:05
   ------------ --------------------------- 3.9/12.3 MB 1.9 MB/s eta 0:00:05
   -------------- ------------------------- 4.5/12.3 MB 1.9 MB/s eta 0:00:05
   ----------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.zeros((2,2))
arr

array([[0., 0.],
       [0., 0.]])

In [9]:
arr = np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

In [10]:
np.random.rand(4)

array([0.05751947, 0.28007709, 0.40085407, 0.02497462])

In [14]:
np.random.randint(5)

4

In [15]:
np.random.randn(4)

array([-0.44652542,  1.70830479, -0.51847474,  1.65174391])

In [16]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
a.shape

(10,)

In [18]:
a.size

10

In [19]:
a = np.array(22)
b = np.array([12,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)
print(b)
print(c)
print(d)

22
[12  2  3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
np.sum(c,axis=0)

[[1 2 3]
 [4 5 6]]


array([ 6, 15])

In [20]:

b = np.array([12,2,3])
print(b.sum())


17


In [24]:
x = np.arange(1,21)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
x = np.arange(1,21)
x.reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
import numpy as np
a = np.array(22)
print(a)         

b = np.array([10, 20, 30, 40])

print(b[0])  
c = np.array([[1, 2, 3],
              [4, 5, 6]])

print(c[1, 1])  

d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(d[0, 1, 1]) 

22
10
5
4
